### ISSUE TITLE
Small window still appears

### ISSUE THREAD

**Issue by elmcapp** [newline-sandbox/rn-macos-menu-bar-app#1]
I followed all of the instructions but small window still appears. I clean the build folder and rerun the project still have small window
<img width="1124" alt="Screen Shot 2022-06-22 at 5 07 58 PM" src="https://user-images.githubusercontent.com/64275658/175136445-80d0b427-d762-41b0-9cc9-848531fea952.png">
<img width="1337" alt="Screen Shot 2022-06-22 at 5 08 28 PM" src="https://user-images.githubusercontent.com/64275658/175136447-5f05a464-88a1-4bf2-8474-ee1fa6b030b0.png">

**Comment by kenchandev** [comment]
Hey! If you cloned this project, then rename its directory from `rn-macos-menu-bar-app` to `rnMacMenubar`. Then, run `npm install` in the root of the project directory and run `pod install` in the project's `macos` directory. Finally, run `npm run build` to build the project. 

I wasn't able to reproduce the issue you encountered (I'm running on macOS Monterey, Intel Processor). Can you see if what I suggested works? If not, then link me to a repository of the code you're working with.

**Comment by elmcapp** [comment]
I have not tried what you suggested yet but I was able to fix the problem and it's running in Development. 

The problem now is that I can't get it to working under Production (release). I get Build fail

ld: warning: option -no_dead_strip_inits_and_terms is obsolete and being ignored
ld: warning: Could not find or use auto-linked library 'swiftCoreData'
ld: warning: Could not find or use auto-linked library 'swiftCoreFoundation'
ld: warning: Could not find or use auto-linked library 'swiftXPC'
ld: warning: Could not find or use auto-linked library 'swiftIOKit'
ld: warning: Could not find or use auto-linked library 'swiftObjectiveC'
ld: warning: Could not find or use auto-linked library 'swiftDispatch'
ld: warning: Could not find or use auto-linked library 'swiftQuartzCore'
ld: warning: Could not find or use auto-linked library 'swiftCore'
ld: warning: Could not find or use auto-linked library 'swiftCoreGraphics'
ld: warning: Could not find or use auto-linked library 'swiftMetal'
ld: warning: Could not find or use auto-linked library 'swiftFoundation'
ld: warning: Could not find or use auto-linked library 'swiftDarwin'
ld: warning: Could not find or use auto-linked library 'swiftAppKit'
ld: warning: Could not find or use auto-linked library 'swiftCoreImage'
Undefined symbols for architecture arm64:
  "__swift_FORCE_LOAD_$_swiftQuartzCore", referenced from:
      __swift_FORCE_LOAD_$_swiftQuartzCore_$_menuapp in AppDelegate.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftQuartzCore_$_menuapp)
  "__swift_FORCE_LOAD_$_swiftMetal", referenced from:
      __swift_FORCE_LOAD_$_swiftMetal_$_menuapp in AppDelegate.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftMetal_$_menuapp)
  "__swift_FORCE_LOAD_$_swiftCoreImage", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreImage_$_menuapp in AppDelegate.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreImage_$_menuapp)
  "__swift_FORCE_LOAD_$_swiftAppKit", referenced from:
      __swift_FORCE_LOAD_$_swiftAppKit_$_menuapp in AppDelegate.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftAppKit_$_menuapp)
  "__swift_FORCE_LOAD_$_swiftCoreGraphics", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreGraphics_$_menuapp in AppDelegate.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreGraphics_$_menuapp)
  "__swift_FORCE_LOAD_$_swiftDispatch", referenced from:
      __swift_FORCE_LOAD_$_swiftDispatch_$_menuapp in AppDelegate.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftDispatch_$_menuapp)
  "__swift_FORCE_LOAD_$_swiftCoreFoundation", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreFoundation_$_menuapp in AppDelegate.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreFoundation_$_menuapp)
  "_swift_unknownObjectRetain", referenced from:
      @objc menuapp.AppDelegate.togglePopover(Swift.AnyObject?) -> () in AppDelegate.o
  "__swift_FORCE_LOAD_$_swiftObjectiveC", referenced from:
      __swift_FORCE_LOAD_$_swiftObjectiveC_$_menuapp in AppDelegate.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftObjectiveC_$_menuapp)
  "__swift_FORCE_LOAD_$_swiftFoundation", referenced from:
      __swift_FORCE_LOAD_$_swiftFoundation_$_menuapp in AppDelegate.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftFoundation_$_menuapp)
  "value witness table for Builtin.UnknownObject", referenced from:
      full type metadata for menuapp.AppDelegate in AppDelegate.o
  "nominal type descriptor for Foundation.URL", referenced from:
      _symbolic _____Sg 10Foundation3URLV in AppDelegate.o
  "static Foundation.Notification._unconditionallyBridgeFromObjectiveC(__C.NSNotification?) -> Foundation.Notification", referenced from:
      @objc menuapp.AppDelegate.applicationDidFinishLaunching(Foundation.Notification) -> () in AppDelegate.o
  "_swift_getTypeByMangledNameInContext", referenced from:
      ___swift_instantiateConcreteTypeFromMangledName in AppDelegate.o
  "__swift_FORCE_LOAD_$_swiftCoreData", referenced from:
      __swift_FORCE_LOAD_$_swiftCoreData_$_menuapp in AppDelegate.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftCoreData_$_menuapp)
  "__swift_FORCE_LOAD_$_swiftDarwin", referenced from:
      __swift_FORCE_LOAD_$_swiftDarwin_$_menuapp in AppDelegate.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftDarwin_$_menuapp)
  "type metadata accessor for Foundation.URL", referenced from:
      menuapp.AppDelegate.applicationDidFinishLaunching(Foundation.Notification) -> () in AppDelegate.o
  "Foundation.URL._bridgeToObjectiveC() -> __C.NSURL", referenced from:
      menuapp.AppDelegate.applicationDidFinishLaunching(Foundation.Notification) -> () in AppDelegate.o
  "__swift_FORCE_LOAD_$_swiftIOKit", referenced from:
      __swift_FORCE_LOAD_$_swiftIOKit_$_menuapp in AppDelegate.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftIOKit_$_menuapp)
  "_swift_isaMask", referenced from:
      menuapp.AppDelegate.applicationDidFinishLaunching(Foundation.Notification) -> () in AppDelegate.o
      menuapp.AppDelegate.togglePopover(Swift.AnyObject?) -> () in AppDelegate.o
  "type metadata accessor for Foundation.Notification", referenced from:
      @objc menuapp.AppDelegate.applicationDidFinishLaunching(Foundation.Notification) -> () in AppDelegate.o
  "static Foundation.URL._unconditionallyBridgeFromObjectiveC(__C.NSURL?) -> Foundation.URL", referenced from:
      menuapp.AppDelegate.applicationDidFinishLaunching(Foundation.Notification) -> () in AppDelegate.o
  "(extension in Foundation):Swift.String._bridgeToObjectiveC() -> __C.NSString", referenced from:
      menuapp.AppDelegate.applicationDidFinishLaunching(Foundation.Notification) -> () in AppDelegate.o
  "_swift_unknownObjectRelease", referenced from:
      @objc menuapp.AppDelegate.togglePopover(Swift.AnyObject?) -> () in AppDelegate.o
  "_swift_endAccess", referenced from:
      menuapp.AppDelegate.statusBarItem.modify : __C.NSStatusItem? with unmangled suffix ".resume.0" in AppDelegate.o
  "__swift_FORCE_LOAD_$_swiftXPC", referenced from:
      __swift_FORCE_LOAD_$_swiftXPC_$_menuapp in AppDelegate.o
     (maybe you meant: __swift_FORCE_LOAD_$_swiftXPC_$_menuapp)
  "_swift_beginAccess", referenced from:
      menuapp.AppDelegate.popover.modify : __C.NSPopover? in AppDelegate.o
      menuapp.AppDelegate.window.modify : __C.NSWindow? in AppDelegate.o
      merged menuapp.AppDelegate.popover.getter : __C.NSPopover? in AppDelegate.o
      merged menuapp.AppDelegate.popover.setter : __C.NSPopover? in AppDelegate.o
      menuapp.AppDelegate.statusBarItem.modify : __C.NSStatusItem? in AppDelegate.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I selected Yes for both project and target for Don't Dead-Strip Inits and Terms. I even used yes for Debug and still got this error

![Screen Shot 2022-06-22 at 10 13 59 PM](https://user-images.githubusercontent.com/64275658/175192640-427ef9af-c586-41f4-b7d9-ec67e7351156.png)
![Screen Shot 2022-06-22 at 10 14 35 PM](https://user-images.githubusercontent.com/64275658/175192735-a7550626-dd6e-4411-899c-e6b725e907b2.png)
![Screen Shot 2022-06-22 at 10 14 43 PM](https://user-images.githubusercontent.com/64275658/175192741-3f9b6132-5910-4a0e-a5c7-f85c524b0a82.png)

**Comment by kenchandev** [comment]
Build the project via `npm run build`. Once the project is built, you will notice in the logs that the application can be found in `Build/Products/Release` directory. Visit this directory and execute the app from there. 

The `npm run build` command already sets the build configuration to release:

`xcodebuild -workspace macos/rnmacmenubar.xcworkspace -scheme rnmacmenubar-macOS -config Release EXCLUDED_ARCHS=arm64`

![](https://www.dl.dropboxusercontent.com/s/uo0sp9dhx92vzyh/fhauuhd9y981.png)

**Comment by elmcapp** [comment]
Runs perfect that way. My question to you is using the ``` -config Release EXCLUDED_ARCHS=arm64```
will this prevent it from running on M1 and M2 chips. Will it run on Intel and Silicone chips native without needing roschetti

**Comment by kenchandev** [comment]
The reason for this environment variable had to do with this issue here for React Native v0.63.0: https://github.com/facebook/react-native/issues/29984. Since "libPods" didn't support `arm64`, I excluded `arm64` from the simulator architectures in the app. It should be able to run on M1 and M2, at least according to an official contributor to the react-native-macos project: https://github.com/microsoft/react-native-macos/pull/908#issuecomment-990602133.

**Comment by elmcapp** [comment]
I was able to figure out how to build and run from Xcode on release scheme without ```-config Release EXCLUDED_ARCHS=arm64```

This fixed all errors I was getting when trying to build and release the app in production (release scheme)
<img width="1140" alt="Screen Shot 2022-06-23 at 8 29 15 AM" src="https://user-images.githubusercontent.com/64275658/175299315-5b300d4f-f9c1-4d27-9cb2-0406f1c2c84a.png">
